Repository alire-project/alire-index, pull requests merged in 2024-07, with the labels that each got.

#1016 Add Cheddar 3.3
  index/ch/cheddar/cheddar-3.3.0.toml
  index/oc/ocarina_lib/ocarina_lib-1.1.0-20070603.toml
Labels: Stale

#1118 GNATprove 14
  index/gn/gnatprove/gnatprove-14.1.1.toml
Labels: unavailable: HOMEBREW, unavailable: MACPORTS

#1150 qplt 20230720.0.0
  index/qp/qplt/qplt-20230720.0.0.toml
  index/ss/ssl/ssl-external.toml
Labels: action needed: fix dependencies
